biolib_version: 2

modules:
    main:
#        image: 'dockerhub://clearlinux/openjdk:latest'
        image: 'dockerhub://simoesrenato/proteomic:latest'        
        command: java -cp "fast-protein-1.0.jar" BiolibMain
#        command: python3 run.py

        working_directory: /home/biolib/
        input_files:
            - COPY / /home/biolib/
        output_files:
            - COPY /home/biolib/ /
        source_files:
            - COPY / /home/biolib/

arguments:
    -
        default_value: input.fasta
        description: 'FASTA file to process 2'
        key: '--input'
        required: true
        type: file
    -
        key: --type_biolib
        description: 'Type of output format options'
        key_value_separator: ','
        default_value: 'csv,tsv,sep,txt'
        type: hidden
        required: false
    -
        key: --subcell
        description: 'Subcellular prediction organism (WolfPSORT)'
        default_value: 'animal'
        type: dropdown
        options:
            'Animal': 'animal'
            'Plant': 'plant'
            'Fungi': 'fungi'
            'No prediction': 'none'
        required: false
    -
        key: --signalp
        description: 'Signal peptides prediction organism (SignalP-5)'
        default_value: 'euk'
        type: hidden
#        options:
#            'Eukarya': 'euk'
#            'Archaea': 'arch'
#            'Gram-positive': 'gram_pos'
#            'Gram-negative': 'gram_neg'
#            'No prediction': 'none'           
        required: false
    -
      key: --output
      description: 'Output name file'
      default_value: 'fastprotein'
      type: hidden
      
    -   
      key: --interpro
      description: 'Do you want to perform remote Interproscan (EBI-WP)search (~1 minute per protein)?'
      default_value: 'false'
      type: radio
      required: false
      options:
         'Yes': 'true'
         'No': 'false'   

    -   
      key: --web-blast
      description: 'Do you want to perform Blast Remote Search (NCBI Web Blast) (~2 minutes per protein)?'
      default_value: 'false'
      type: radio
      required: false
      options:
         'Yes': 'true'
         'No': 'false'   
      sub_arguments:
         'true':
                -
                    key: --blastdb
                    description: 'Blast Database'
                    default_value: 'swissprot'
                    type: dropdown
                    options:
                        'Swiss-Prot': 'swissprot'
                        'NR': 'nr'
                    required: false
                -
                    key: --blast-timeout
                    description: 'Blast Timeout (seconds)'
                    default_value: '60'
                    type: text
                    required: false
      
main_output_file: /output.md
remote_hosts:
    - 'www.ebi.ac.uk'
    - 'blast.ncbi.nlm.nih.gov'